name: india_air_quality_json

# Controls when the workflow will run
on:
  # Trigger the workflow manually through GitHub UI
  #workflow_dispatch:
  # Uncomment below for cron job
   schedule:
     - cron: '0 0 * * *'  # Runs every day

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps to run in the "build" job
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v3

      # Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Ensure using Python 3.8

      # Install pip and dependencies
      - name: Install dependencies
        run: |
          echo "Home directory: $GITHUB_WORKSPACE"
          echo -----------------------------------------------------------------------
          pip install --upgrade pip  # Upgrade pip
          echo -----------------------------------------------------------------------

          # Install snowflake-snowpark-python without [pandas] extra
          pip install snowflake-snowpark-python  # Install Snowpark without pandas
          
          # If pandas is needed separately, install it
          pip install pandas

          echo -----------------------------------------------------------------------
          ls -la
          pwd
          echo -----------------------------------------------------------------------

      # Run the Python script
      - name: Run ingest-api-data.py
        run: |
          python $GITHUB_WORKSPACE/ingest-api-data.py
